- RangeViolation:
    Columns:
    - Application order
    Params:
      severity: 0.04
      sampling: CAR
      min_value: 1
      max_value: 10
      strategy: below_min
      violation_factor: 1.5
      random_state: null
