- GaussianNoise:
    Columns:
    - YearsAtCompany
    Params:
      severity: 0.3
      sampling: CAR
- ColumnInserting:
    Columns:
    - EmpID
    Params:
      severity: 1
      sampling: CAR
      corrupt_strategy: add_prefix
