- RangeViolation:
    Columns:
    - c13
    Params:
      severity: 0.05
      sampling: CAR
      min_value: 0
      max_value: 200
      strategy: random
      violation_factor: 1.5
      random_state: null
