- RangeViolation:
    Columns:
    - Age
    Params:
      severity: 0.03
      sampling: CAR
      min_value: 18
      max_value: null
      strategy: below_min
      violation_factor: 1.5
      random_state: null
- RangeViolation:
    Columns:
    - Age
    Params:
      severity: 0.03
      sampling: CAR
      min_value: null
      max_value: 65
      strategy: above_max
      violation_factor: 1.5
      random_state: null
