- MaskValues:
    Columns:
    - Meta_score
    Params:
      severity: 0.1
      sampling: CAR
- OutlierInjection:
    Columns:
    - IMDB_Rating
    Params:
      severity: 0.03
      sampling: CAR
      strategy: zscore_based
      factor: 4.0
      random_state: null
